{ pkgs, config, ... }:
let
  # git-hooks.nix installs `.pre-commit-config.yaml` and git hooks into
  # `git rev-parse --show-toplevel` of the directory the shell is entered
  # from, so `nix develop /path/to/this-repo#ci` run inside another checkout
  # would plant this repository's hooks there. `ownRepoOnly` runs a snippet
  # only when that toplevel is this repository, recognised by a `flake.nix`
  # identical to the one this shell was evaluated from; anything it cannot
  # establish counts as another repository, so it fails safe.
  # tests/test_dev_shell_writes_nothing_elsewhere.sh
  ownRepoOnly = script: ''
    _own_repo_root="$(${pkgs.git}/bin/git rev-parse --show-toplevel 2>/dev/null || true)"
    if [ -n "$_own_repo_root" ] && [ -f "$_own_repo_root/flake.nix" ] \
      && [ "$(${pkgs.coreutils}/bin/sha256sum "$_own_repo_root/flake.nix" | ${pkgs.coreutils}/bin/cut -d' ' -f1)" \
        = "${builtins.hashFile "sha256" ../flake.nix}" ]; then
    ${script}
    # git-hooks.nix's installer leaves core.hooksPath as the RELATIVE
    # `.git/hooks`, in the config every worktree shares. A linked worktree
    # cannot resolve it (there `.git` is a file), so git silently runs no
    # hooks there. Point it at the common hooks directory instead.
    if [ "$(${pkgs.git}/bin/git config --local --get core.hooksPath 2>/dev/null)" = .git/hooks ]; then
      ${pkgs.git}/bin/git config --local core.hooksPath "$(${pkgs.git}/bin/git rev-parse --path-format=absolute --git-common-dir)/hooks"
    fi
    # The installer moves each Reprobuild hook dispatcher aside to
    # `<hook>.legacy` and puts pre-commit's shim in its slot, so the managed
    # hook (for pre-push, the publication gate) runs only by accident. Put the
    # dispatcher back and chain the shim as `<hook>.repro-local`, which the
    # dispatcher runs: the layout `repro hooks ensure --vcs` produces.
    _hooks="$(${pkgs.git}/bin/git rev-parse --path-format=absolute --git-path hooks 2>/dev/null || true)"
    for _legacy in "$_hooks"/*.legacy; do
      [ -f "$_legacy" ] && grep -q 'reprobuild hook dispatcher' "$_legacy" || continue
      _slot="''${_legacy%.legacy}"
      if [ -f "$_slot" ] && grep -q 'reprobuild hook dispatcher' "$_slot"; then
        rm -f "$_legacy"
      elif [ ! -e "$_slot" ] || grep -Eq '^# File generated by (pre-commit|prek)' "$_slot"; then
        if [ -f "$_slot.repro-local" ] && ! grep -Eq '^# File generated by (pre-commit|prek)' "$_slot.repro-local"; then
          echo "git-hooks: $_slot.repro-local is your own hook; run 'repro hooks ensure --vcs' to reconcile." >&2
          continue
        fi
        if [ -e "$_slot" ]; then mv -f "$_slot" "$_slot.repro-local"; fi
        mv -f "$_legacy" "$_slot"
      else
        echo "git-hooks: $_slot is not a pre-commit shim; run 'repro hooks ensure --vcs' to reconcile." >&2
      fi
    done
    unset _hooks _legacy _slot
    fi
    unset _own_repo_root
  '';
in
pkgs.mkShellNoCC {
  packages = with pkgs; [
    jq
    nix-eval-jobs
    figlet
  ];

  shellHook = ''
    figlet -w"''${COLUMNS:-80}" "nix-blockchain-development"
  ''
  + ownRepoOnly config.pre-commit.installationScript;
}
