cargo-features = ["edition2021"]
[package]
name = "trace-malloc-free"
version = "0.1.0"
authors = ["Nick Fitzgerald <fitzgen@gmail.com>"]

[dependencies]
quicli = "0.3"
duct = "0.11.0"
regex = "1.0.1"
