name: 'Update Flake Packages ❄️'
on:
  workflow_dispatch:
  schedule:
    - cron: '0 0 * * *' # https://crontab.guru/#0_0_*_*_*

jobs:
  update-flake-packages:
    uses: metacraft-labs/nixos-modules/.github/workflows/update-flake-packages.yml@main
    secrets:
      CACHIX_AUTH_TOKEN: ${{ secrets.CACHIX_AUTH_TOKEN }}
      CREATE_PR_APP_ID: ${{ secrets.APP_ID }}
      CREATE_PR_APP_PRIVATE_KEY: ${{ secrets.APP_PRIVATE_KEY }}
