name: "Update Flake Packages ❄️"
on:
  workflow_dispatch:
  schedule:
    - cron: "0 0 * * *" # https://crontab.guru/#0_0_*_*_*

jobs:
  update-flake-packages:
    uses: metacraft-labs/nixos-modules/.github/workflows/update-flake-packages.yml@feat/reusable-workflow
    secrets: inherit
